// components/home/HomeNews.vue
<script setup lang="ts">
import { contentfulImageUrl } from "~/utils/newsContent";

type Article = {
  sys: { id: string };
  fields: {
    header: string;
    date: string;
    image?: { fields?: { file?: { url?: string } } };
  };
};
const { $contentful } = useNuxtApp();
const {
  data: articles,
  error,
  status,
  refresh,
} = await useAsyncData(
  "home-latest-news",
  async () => {
    const result = (await $contentful.getEntries({
      content_type: "news",
      order: "-fields.date",
      limit: 3,
    })) as { items: Article[] };
    return result.items.map((article) => {
      const url = contentfulImageUrl(article.fields.image?.fields?.file?.url, {
        width: 900,
      });
      return {
        id: article.sys.id,
        title: article.fields.header,
        date: article.fields.date,
        image: url,
        dateLabel: new Intl.DateTimeFormat("ru-RU", {
          day: "numeric",
          month: "long",
          year: "numeric",
          timeZone: "UTC",
        }).format(new Date(article.fields.date)),
      };
    });
  },
  { default: () => [] },
);
</script>

<template>
  <section class="ref-news ref-container" aria-labelledby="news-title">
    <header>
      <h2 id="news-title" class="ref-title">Новости</h2>
      <NuxtLink to="/news" class="ref-link"
        >Все новости <span aria-hidden="true">→</span></NuxtLink
      >
    </header>
    <p v-if="status === 'pending'" class="ref-news__status" role="status">
      Загрузка новостей…
    </p>
    <div v-else-if="error" class="ref-news__status">
      <p>Не удалось загрузить новости завода.</p>
      <button type="button" class="ref-link" @click="refresh()">
        Попробовать ещё раз →
      </button>
    </div>
    <div v-else-if="articles.length" class="ref-news__grid">
      <NuxtLink
        v-for="(article, index) in articles"
        :key="article.id"
        :to="`/news/${article.id}`"
        class="ref-news__item"
        :class="{ 'ref-news__item--featured': index === 0 }"
        ><img
          v-if="article.image"
          :src="article.image"
          :alt="article.title"
          width="900"
          height="600"
          loading="lazy"
        />
        <div class="ref-news__copy">
          <time :datetime="article.date">{{ article.dateLabel }}</time>
          <h3>{{ article.title }}</h3>
          <span class="ref-news__more"
            >Читать <span aria-hidden="true">→</span></span
          >
        </div></NuxtLink
      >
    </div>
    <p v-else class="ref-news__status">
      Новые публикации появятся в разделе новостей.
    </p>
  </section>
</template>

// migration/next/src/components/site/home/HomeNews.tsx
import Link from 'next/link';
import { formatHomeNewsDate } from '@/lib/home-content';
import { news, newsPath, publicMedia } from '@/lib/public-content';

export async function HomeNews() {
  const records = (await news()).slice(0, 3);
  const articles = await Promise.all(
    records.map(async (article) => {
      const media = await publicMedia(article.image);
      return {
        id: article.id,
        href: newsPath(article),
        title: article.title,
        date: article.publishedAt,
        dateLabel: article.publishedAt
          ? formatHomeNewsDate(article.publishedAt)
          : null,
        image: media?.url ?? null,
      };
    }),
  );

  return (
    <section className="ref-news ref-container" aria-labelledby="news-title">
      <header>
        <h2 id="news-title" className="ref-title">
          Новости
        </h2>
        <Link href="/news" className="ref-link">
          Все новости <span aria-hidden="true">→</span>
        </Link>
      </header>
      {articles.length ? (
        <div className="ref-news__grid">
          {articles.map((article, index) => (
            <Link
              key={article.id}
              href={article.href}
              className={[
                'ref-news__item',
                index === 0 ? 'ref-news__item--featured' : '',
              ]
                .filter(Boolean)
                .join(' ')}
            >
              {article.image ? (
                <img
                  src={article.image}
                  alt={article.title}
                  width={900}
                  height={600}
                  loading="lazy"
                />
              ) : null}
              <div className="ref-news__copy">
                {article.date && article.dateLabel ? (
                  <time dateTime={article.date}>{article.dateLabel}</time>
                ) : null}
                <h3>{article.title}</h3>
                <span className="ref-news__more">
                  Читать <span aria-hidden="true">→</span>
                </span>
              </div>
            </Link>
          ))}
        </div>
      ) : (
        <p className="ref-news__status">
          Новые публикации появятся в разделе новостей.
        </p>
      )}
    </section>
  );
}
