// pages/legal/index.vue
<template>
  <LegalPage />
</template>

<script setup lang="ts">
import { PAGE_SEO } from "~/utils/siteSeo";
import LegalPage from "~/components/legal/LegalPage.vue";
import { LEGAL_HERO } from "~/utils/legalContent";

usePageSeo(PAGE_SEO.legal);

useHead({
  link: [
    {
      rel: "preload",
      as: "image",
      href: LEGAL_HERO.image,
      type: "image/webp",
    },
  ],
});
</script>

// migration/next/src/app/(site)/legal/page.tsx
import { LegalPage } from '@/components/site/static/legal/LegalPage';
import { JsonLd } from '@/components/site/Content';
import { LEGAL_HERO } from '@/lib/static-content/legal';
import { breadcrumbJsonLd, PAGE_SEO, pageMetadata } from '@/lib/static-content/page-seo';

export const metadata = pageMetadata({
  ...PAGE_SEO.legal,
  ogImage: `https://aokemz.ru${LEGAL_HERO.image}`,
});

export default function LegalRoute() {
  return (
    <>
      <link rel="preload" as="image" href={LEGAL_HERO.image} type="image/webp" />
      <JsonLd
        value={breadcrumbJsonLd([
          { name: 'Главная', path: '/' },
          { name: 'Правовая информация', path: '/legal' },
        ])}
      />
      <LegalPage />
    </>
  );
}
