// pages/about/index.vue
<template>
  <AboutPage />
</template>

<script setup lang="ts">
import { PAGE_SEO } from "~/utils/siteSeo";
import AboutPage from "~/components/about/AboutPage.vue";
import { ABOUT_HERO } from "~/utils/aboutContent";

usePageSeo(PAGE_SEO.about);

useHead({
  link: [
    {
      rel: "preload",
      as: "image",
      href: ABOUT_HERO.image,
      type: "image/webp",
    },
  ],
});
</script>

// migration/next/src/app/(site)/about/page.tsx
import { AboutPage } from '@/components/site/static/about/AboutPage';
import { JsonLd } from '@/components/site/Content';
import { ABOUT_HERO } from '@/lib/static-content/about';
import { breadcrumbJsonLd, PAGE_SEO, pageMetadata } from '@/lib/static-content/page-seo';

export const metadata = pageMetadata({
  ...PAGE_SEO.about,
  ogImage: `https://aokemz.ru${ABOUT_HERO.image}`,
});

export default function AboutRoute() {
  return (
    <>
      <link rel="preload" as="image" href={ABOUT_HERO.image} type="image/webp" />
      <JsonLd
        value={breadcrumbJsonLd([
          { name: 'Главная', path: '/' },
          { name: 'О заводе', path: '/about' },
        ])}
      />
      <AboutPage />
    </>
  );
}
