// components/about/AboutCta.vue
<template>
  <section class="abt-cta" aria-labelledby="about-cta-title">
    <div class="ref-container abt-cta__inner">
      <div>
        <p class="abt-cta__label">Технический отдел</p>
        <h2 id="about-cta-title">Обсудить задачу<br />с техническим отделом</h2>
        <p class="abt-cta__lead">
          Подберём исполнение под параметры машины и подготовим опросный лист.
        </p>
      </div>
      <HomeActionButton class="abt-cta__action" to="/contacts" on-dark>Связаться</HomeActionButton>
      <p class="abt-cta__aside">Электрические машины<br />для карьерной техники</p>
    </div>
  </section>
</template>

// migration/next/src/components/site/static/about/AboutCta.tsx
import { ActionButton } from '../ActionButton';

export function AboutCta() {
  return (
    <section className="abt-cta" aria-labelledby="about-cta-title">
      <div className="ref-container abt-cta__inner">
        <div>
          <p className="abt-cta__label">Технический отдел</p>
          <h2 id="about-cta-title">
            Обсудить задачу
            <br />с техническим отделом
          </h2>
          <p className="abt-cta__lead">
            Подберём исполнение под параметры машины и подготовим опросный лист.
          </p>
        </div>
        <ActionButton className="abt-cta__action" to="/contacts" onDark>
          Связаться
        </ActionButton>
        <p className="abt-cta__aside">
          Электрические машины
          <br />
          для карьерной техники
        </p>
      </div>
    </section>
  );
}
